Increase work flow file to make it fail

diff --git a/.github/workflows/pr-java-ci.yml b/.github/workflows/pr-java-ci.yml
--- a/.github/workflows/pr-java-ci.yml
+++ b/.github/workflows/pr-java-ci.yml
@@ -35,6 +35,7 @@ jobs:
         run: |
           mvn -B package --file extra/pom.xml | tee build_output.txt
           echo "exit_code=1" >> "$GITHUB_OUTPUT"
+
       - name: Write to GITHUB_OUTPUT and debug
         id: example
         run: |
@@ -57,3 +58,9 @@ jobs:
           token: ${{ secrets.GITHUB_TOKEN }}
           issue-number: ${{ github.event.pull_request.number }}
           body-path: comment.txt
+
+      - name: Fail if '[ERROR]' is found in logs
+        run: |
+          if grep -q "\[ERROR\]" build_output.txt; then
+            exit 1  # This makes the check fail
+          fi
